name: 'Merge Queue init'
description: 'handles a merge queue'
inputs:
  trigger:  # id of input
    description: 'the trigger keyword to add PR to queue'
    required: false
    default: '/merging'
  channel:  # id of input
    description: 'the channel to use as the queue'
    required: false
    default: 'merge-queue'
outputs:
  status: # id of output
    description: 'status of the build run: TRIGGER_NOT_FOUND, ALREADY_CLOSED, ALREADY_QUEUED, ADDED_TO_QUEUE'
runs:
  using: 'node12'
  main: 'src/index.js'